
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tk_DECREMENTO = 54;
  public static final int res_IMPRIMIR = 22;
  public static final int res_REPETIR = 19;
  public static final int res_HASTA = 15;
  public static final int tk_MENQUE = 49;
  public static final int res_METODOCONP = 38;
  public static final int res_ENTONCES = 25;
  public static final int res_METODO = 18;
  public static final int ENTERO = 3;
  public static final int tk_CONCAT = 48;
  public static final int res_FINMETODO = 31;
  public static final int res_FIN = 8;
  public static final int res_CONINCREM = 36;
  public static final int BLANCOS = 6;
  public static final int res_CARACTER = 23;
  public static final int res_ELSE = 37;
  public static final int tk_ASIGNAFLECHA = 55;
  public static final int res_MIENTRAS = 27;
  public static final int res_CONVALOR = 29;
  public static final int res_FINFUNCION = 32;
  public static final int res_ELSEIF = 11;
  public static final int IDENTIFICADOR = 2;
  public static final int res_FUNCION = 35;
  public static final int CARACTER = 4;
  public static final int tk_LLAVIZQ = 43;
  public static final int res_PARA = 12;
  public static final int EOF = 0;
  public static final int DECIMAL = 5;
  public static final int res_FINMIENTRAS = 34;
  public static final int tk_PARIZQ = 45;
  public static final int error = 1;
  public static final int res_SI = 9;
  public static final int res_FINPARA = 20;
  public static final int tk_MAS = 39;
  public static final int res_HASTAQ = 30;
  public static final int tk_CADENA = 52;
  public static final int res_FINSEGUN = 28;
  public static final int res_SEGUN = 13;
  public static final int res_HACER = 14;
  public static final int res_INGRESAR = 21;
  public static final int res_IMPRIMIRNL = 33;
  public static final int tk_MAYQUE = 50;
  public static final int tk_POR = 41;
  public static final int tk_IGUAL = 51;
  public static final int tk_DIVIDIDO = 40;
  public static final int res_FINSI = 17;
  public static final int tk_LLAVDER = 44;
  public static final int res_RETORNAR = 24;
  public static final int res_EJECUTAR = 26;
  public static final int res_INICIO = 7;
  public static final int tk_INCREMENTO = 53;
  public static final int tk_PTCOMA = 42;
  public static final int res_COMO = 10;
  public static final int tk_MENOS = 47;
  public static final int tk_PARDER = 46;
  public static final int res_NUMERO = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "ENTERO",
  "CARACTER",
  "DECIMAL",
  "BLANCOS",
  "res_INICIO",
  "res_FIN",
  "res_SI",
  "res_COMO",
  "res_ELSEIF",
  "res_PARA",
  "res_SEGUN",
  "res_HACER",
  "res_HASTA",
  "res_NUMERO",
  "res_FINSI",
  "res_METODO",
  "res_REPETIR",
  "res_FINPARA",
  "res_INGRESAR",
  "res_IMPRIMIR",
  "res_CARACTER",
  "res_RETORNAR",
  "res_ENTONCES",
  "res_EJECUTAR",
  "res_MIENTRAS",
  "res_FINSEGUN",
  "res_CONVALOR",
  "res_HASTAQ",
  "res_FINMETODO",
  "res_FINFUNCION",
  "res_IMPRIMIRNL",
  "res_FINMIENTRAS",
  "res_FUNCION",
  "res_CONINCREM",
  "res_ELSE",
  "res_METODOCONP",
  "tk_MAS",
  "tk_DIVIDIDO",
  "tk_POR",
  "tk_PTCOMA",
  "tk_LLAVIZQ",
  "tk_LLAVDER",
  "tk_PARIZQ",
  "tk_PARDER",
  "tk_MENOS",
  "tk_CONCAT",
  "tk_MENQUE",
  "tk_MAYQUE",
  "tk_IGUAL",
  "tk_CADENA",
  "tk_INCREMENTO",
  "tk_DECREMENTO",
  "tk_ASIGNAFLECHA"
  };
}

