
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int res_IMPRIMIR = 24;
  public static final int IDENTIFICADOR = 2;
  public static final int tk_MAS = 54;
  public static final int res_VERDADERO = 6;
  public static final int res_MAYOR = 45;
  public static final int res_FINSEGUN = 30;
  public static final int res_MIENTRAS = 29;
  public static final int res_FINMIENTRAS = 36;
  public static final int res_IMPRIMIRNL = 35;
  public static final int res_CADENA = 41;
  public static final int res_BOOLEAN = 42;
  public static final int res_FALSO = 7;
  public static final int res_CARACTER = 25;
  public static final int res_AND = 52;
  public static final int res_FINMETODO = 33;
  public static final int tk_CADENA = 68;
  public static final int res_EJECUTAR = 28;
  public static final int res_ENTONCES = 27;
  public static final int res_MENORIGUAL = 47;
  public static final int res_FINPARA = 22;
  public static final int res_HACER = 16;
  public static final int res_FINSI = 19;
  public static final int res_RETORNAR = 26;
  public static final int tk_DIVIDIDO = 55;
  public static final int tk_IGUAL = 67;
  public static final int tk_LLAVDER = 60;
  public static final int tk_PARIZQ = 61;
  public static final int ENTERO = 3;
  public static final int tk_PTCOMA = 57;
  public static final int res_MAYORIGUAL = 48;
  public static final int res_HASTA = 17;
  public static final int res_INGRESAR = 23;
  public static final int tk_MENOS = 63;
  public static final int res_MENOR = 46;
  public static final int BLANCOS = 8;
  public static final int tk_COMA = 58;
  public static final int tk_INCREMENTO = 69;
  public static final int DECIMAL = 5;
  public static final int res_NOT = 53;
  public static final int res_OR = 51;
  public static final int res_FINFUNCION = 34;
  public static final int tk_DECREMENTO = 70;
  public static final int res_ELSEIF = 13;
  public static final int res_INICIO = 9;
  public static final int res_POTENCIA = 43;
  public static final int res_CONINCREM = 38;
  public static final int res_NUMERO = 18;
  public static final int res_METODO = 20;
  public static final int res_COMO = 12;
  public static final int res_REPETIR = 21;
  public static final int res_MOD = 44;
  public static final int res_SEGUN = 15;
  public static final int EOF = 0;
  public static final int res_PARA = 14;
  public static final int tk_POR = 56;
  public static final int res_METODOCONP = 40;
  public static final int CARACTER = 4;
  public static final int tk_MENQUE = 65;
  public static final int res_CONVALOR = 31;
  public static final int error = 1;
  public static final int tk_MAYQUE = 66;
  public static final int res_ESIGUAL = 49;
  public static final int res_FIN = 10;
  public static final int res_ELSE = 39;
  public static final int res_HASTAQ = 32;
  public static final int tk_LLAVIZQ = 59;
  public static final int tk_CONCAT = 64;
  public static final int tk_ASIGNAFLECHA = 71;
  public static final int res_SI = 11;
  public static final int res_ESDIFERENTE = 50;
  public static final int tk_PARDER = 62;
  public static final int res_FUNCION = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "ENTERO",
  "CARACTER",
  "DECIMAL",
  "res_VERDADERO",
  "res_FALSO",
  "BLANCOS",
  "res_INICIO",
  "res_FIN",
  "res_SI",
  "res_COMO",
  "res_ELSEIF",
  "res_PARA",
  "res_SEGUN",
  "res_HACER",
  "res_HASTA",
  "res_NUMERO",
  "res_FINSI",
  "res_METODO",
  "res_REPETIR",
  "res_FINPARA",
  "res_INGRESAR",
  "res_IMPRIMIR",
  "res_CARACTER",
  "res_RETORNAR",
  "res_ENTONCES",
  "res_EJECUTAR",
  "res_MIENTRAS",
  "res_FINSEGUN",
  "res_CONVALOR",
  "res_HASTAQ",
  "res_FINMETODO",
  "res_FINFUNCION",
  "res_IMPRIMIRNL",
  "res_FINMIENTRAS",
  "res_FUNCION",
  "res_CONINCREM",
  "res_ELSE",
  "res_METODOCONP",
  "res_CADENA",
  "res_BOOLEAN",
  "res_POTENCIA",
  "res_MOD",
  "res_MAYOR",
  "res_MENOR",
  "res_MENORIGUAL",
  "res_MAYORIGUAL",
  "res_ESIGUAL",
  "res_ESDIFERENTE",
  "res_OR",
  "res_AND",
  "res_NOT",
  "tk_MAS",
  "tk_DIVIDIDO",
  "tk_POR",
  "tk_PTCOMA",
  "tk_COMA",
  "tk_LLAVIZQ",
  "tk_LLAVDER",
  "tk_PARIZQ",
  "tk_PARDER",
  "tk_MENOS",
  "tk_CONCAT",
  "tk_MENQUE",
  "tk_MAYQUE",
  "tk_IGUAL",
  "tk_CADENA",
  "tk_INCREMENTO",
  "tk_DECREMENTO",
  "tk_ASIGNAFLECHA"
  };
}

